/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package curlaawsmanager.edu.cis.uab;

import curlaawsmanager.edu.cis.uab.awshelper.SQSHelper;
import curlaawsmanager.edu.cis.uab.util.ZLogger;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author zawoad
 */
public class FileSourceManager extends javax.swing.JDialog {

    /**
     * Creates new form S3SourceControlManager
     */
    public FileSourceManager(JFrame parent) {
        super(parent, true);
        setTitle("Manage Local URL File Source");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStartIndex = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStepLimit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStopLimit = new javax.swing.JTextField();
        jbtStart = new javax.swing.JButton();
        jbtCance = new javax.swing.JButton();
        jbtFileChooser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("URL File");

        txtFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Start Index");

        txtStartIndex.setText("1");

        jLabel4.setText("Step Limit");

        txtStepLimit.setText("2");

        jLabel5.setText("Stop Limit");

        txtStopLimit.setText("10");

        jbtStart.setText("Start Deduplication");
        jbtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtStartActionPerformed(evt);
            }
        });

        jbtCance.setText("Close");
        jbtCance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCanceActionPerformed(evt);
            }
        });

        jbtFileChooser.setText("Choose File");
        jbtFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCance, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStopLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStepLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStartIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFileChooser)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStartIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStepLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStopLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtStartActionPerformed
        // TODO add your handling code here:
        try {
            
            parseFile(txtFileName.getText());
        } catch (Exception ex) {
            ZLogger.e(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtStartActionPerformed

    private void jbtCanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCanceActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtCanceActionPerformed

    private void txtFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileNameActionPerformed

    private void jbtFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFileChooserActionPerformed
        // TODO add your handling code here:
         final JFileChooser jfcProof = new JFileChooser();
                jfcProof.setDialogType(JFileChooser.OPEN_DIALOG);
                jfcProof.showDialog(jbtFileChooser, null);
                File selectedFile = jfcProof.getSelectedFile();
                txtFileName.setText(selectedFile.getAbsolutePath());
                
    }//GEN-LAST:event_jbtFileChooserActionPerformed

    private void parseFile(String filePath)
    {
        SQSHelper sqsHelper = SQSHelper.SQSInstance();
        FileInputStream in = null;
        List<String> urlList = new ArrayList<>();
        long recordCounter=1;
        try {
            long startIndex = Long.parseLong(txtStartIndex.getText());
            long stepLimit = Long.parseLong(txtStepLimit.getText());
            long stopLimit = Long.parseLong(txtStopLimit.getText());
            File f = new File(filePath);
            in = new FileInputStream(f);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
            String strLine;
            for(int i=1; i< startIndex; i++)
                br.readLine();
            
            while ((strLine = br.readLine()) != null) {
                
                if (recordCounter > stopLimit) 
                {
                    break;
                }
                urlList.add(strLine);
                System.out.println("strLine = " + strLine);
                 if ((recordCounter % stepLimit) == 0) {
                    sqsHelper.sendMessageToQueueInRoundRobin(urlList);
                    ZLogger.d("---------------------------------------------");
                    ZLogger.d((recordCounter) + " URL Sent.");
                    urlList.clear();
                }
                recordCounter++;
            }
            
        }catch(NumberFormatException nex)
        {
            
        }
        catch (FileNotFoundException ex) {
            ZLogger.e(ex.getLocalizedMessage());
        } catch (IOException ex) {
            ZLogger.e(ex.getLocalizedMessage());
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                ZLogger.e(ex.getLocalizedMessage());
            }
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtCance;
    private javax.swing.JButton jbtFileChooser;
    private javax.swing.JButton jbtStart;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtStartIndex;
    private javax.swing.JTextField txtStepLimit;
    private javax.swing.JTextField txtStopLimit;
    // End of variables declaration//GEN-END:variables
    private static final String RUN_S3FETCHER_SCRIPT = "/home/zawoad/Documents/Dropbox/NetBeansWorkspace/CurlaAWSManager/run_s3fetcher.sh";
    private static final String STOP_S3FETCHER_SCRIPT = "/home/zawoad/Documents/Dropbox/NetBeansWorkspace/CurlaAWSManager/stop_s3fetcher.sh";

}
